server:
  port: 8080
  forward-headers-strategy: native

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/java_app_db}
    username: ${POSTGRES_USER:java_user}
    password: ${POSTGRES_PASSWORD:your_local_password_here}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false


logging:
  level:
    org.springframework.security: DEBUG
    
