name: Deploy LifeGuide to Homeserver

on:
  push:
    branches:
      - main  # Startet, wenn du auf main pushst

jobs:
  deploy:
    runs-on: self-hosted  # Das nutzt deinen lokalen Runner!
    
    steps:
      - name: Code vom Repository herunterladen
        uses: actions/checkout@v4

      - name: Alte Container stoppen und Neue bauen
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_AUTH0_DOMAIN: ${{ secrets.VITE_AUTH0_DOMAIN }}
          VITE_AUTH0_CLIENT_ID: ${{ secrets.VITE_AUTH0_CLIENT_ID }}
          VITE_AUTH0_AUDIENCE: ${{ secrets.VITE_AUTH0_AUDIENCE }}
        run: |
          docker compose down
          docker compose up -d --build