name: Deploy LifeGuide to Homeserver

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Download code from repository
        uses: actions/checkout@v4

      - name: Stop old containers and build new ones
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_AUTH0_DOMAIN: ${{ secrets.VITE_AUTH0_DOMAIN }}
          VITE_AUTH0_CLIENT_ID: ${{ secrets.VITE_AUTH0_CLIENT_ID }}
          VITE_AUTH0_AUDIENCE: ${{ secrets.VITE_AUTH0_AUDIENCE }}
        run: |
          docker compose -f docker-compose.yml down
          docker compose -f docker-compose.yml up -d --build